#!/usr/bin/env bash

# Set up variables
project_dir=$(git rev-parse --show-toplevel)
cd "$project_dir" || exit 1
project_name="Lolgato"
app_path="build/$project_name.app"

# Build the app
./scripts/archive

# Create DMG filename with version
dmg_filename="${project_name}.dmg"
dmg_path="build/$dmg_filename"

# Build the DMG
dmgbuild -s dmgbuild_settings.py -D app="$app_path" "$project_name" "$dmg_path"

echo "Build and packaging complete. DMG created: $dmg_path"

# Notarize the DMG
echo "Submitting DMG for notarization..."
xcrun notarytool submit "$dmg_path" --wait --apple-id "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --team-id "$APPLE_TEAM_ID"

# Staple the ticket to the DMG
echo "Stapling notarization ticket to DMG..."
xcrun stapler staple "$dmg_path"

echo "Build, packaging, and notarization complete. Notarized DMG available at: $dmg_path"
